FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /app/product_catalog

CMD ["gunicorn", "product_catalog.wsgi:application", "--bind", "0.0.0.0:$PORT"]





# version: '3.8'
# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: catalog_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
#   web:
#     build: .
#     command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     env_file: .env
#     depends_on:
#       - db
# volumes:
#   db-data:
