# Generated by Django 5.2.6 on 2025-09-24 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_remove_product_image_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
