# Generated by Django 5.2.6 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productimage_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
