# Generated by Django 5.2.6 on 2025-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productimage_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
