# Generated by Django 5.2.6 on 2025-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_add_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cloudinary_url',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
