# Generated by Django 5.2.6 on 2025-09-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
